### ISSUE TITLE
Cannot be used with inliners like webpack

### ISSUE THREAD

**Issue by FallingSnow** [CytoDev/LightDMMock#4]
https://github.com/CytoDev/LightDMMock/blob/dev/src/LightDMMock.js#L73 breaks usage with webpack.

**Comment by cytodev** [comment]
How do you suggest solving this? I have little to no experience with webpack to be honest...

**Comment by FallingSnow** [comment]
I will move material2 back over to master when I get a chance and see if I can sort out some of the problems to let you know the best way to go about them. Hopefully soon...

**Comment by cytodev** [comment]
@FallingSnow It's been a while, have you found a way to go about this?

**Comment by FallingSnow** [comment]
Yes [I did figure this out](https://github.com/FallingSnow/LightDMMock/commit/12bacd3ebd5bceb25183e3220b245f0480a2f9e9).

___

Kind of a funny coincidence that you messaged me today. Like 3 days ago I got back into this login screen thing after taking a really long break (been using GDM because lightdm doesn't support wayland sessions). I don't think I will be putting any more effort into maintaining anything having to do with lightdm.

Instead I have been looking into writing my own login manager for some time. I've always wanted it to support Html (and CSS+JS) templating. About 3 days ago I came across [webview](https://github.com/zserge/webview) and have been [trying to get that to work](https://github.com/zserge/webview/issues/218). I'm writing this in rust because webview has rust bindings and I want to use [Smithay](https://github.com/Smithay/smithay). I've already gotten a compositor to run with Smithay before and I've already written async message passing between Rust<->JS into the project I currently have using webview.

There are going be a few hurdles:
* Pam authentication (I already have a working example)
* **The compositor** (This one's gonna be deep)
* Working with Webkit2gtk (basically safari 11)
* Probably a lot more!

But I'm looking forward to it. If your interested in testing it out when I get it to work (maybe a month from now, if ever...) or better yet, wanna work on it together, just let me know.

Sorry for the rant :P

**Comment by cytodev** [comment]
Oh wow, I must say I didn't expect such a detailed response. Thanks! As soon as I clicked the first link it all started coming back to me, I had indeed merged your edits back into master shortly after the issue was opened but I seemed to have forgotten to close it.

Funny how some things seem to coincide... I only planned on clicking trough some open issues and dropping comments in order to have them resolved soon-ish.

An entirely new greeter in Rust seems like a very cool project! I would love to help, but sadly I have little to no knowledge on Rust's syntax -- and time has become a very scarce resource combined with my job and travel time. Please do let me know when you have an alpha or beta release though, I would love to take it (and the obviously well-documented API 😜) out for a spin!

P.S.
![image](https://user-images.githubusercontent.com/5646869/50113152-66a91e80-0241-11e9-806c-3e3a9dc204e9.png)
😂😂😂👌

**Comment by FallingSnow** [comment]
> P.S.
> ![image](https://user-images.githubusercontent.com/5646869/50113152-66a91e80-0241-11e9-806c-3e3a9dc204e9.png)

That was the best part :D

> obviously well-documented API

Of course! :)

I'll keep you up to date on when I have an alpha to try.
